#!/usr/bin/env ruby
# frozen_string_literal: true

$:.unshift(File.expand_path("../lib", __dir__))
require "yarv"

# If we're dumping instructions, then we're going to walk through the compiled
# instructions and print each one out in turn.
if ARGV.first == "--dump=insns"
  ARGV.shift

  # Check if we are reading directly from a string with -e.
  compiled =
    if ARGV.first == "-e"
      ARGV.shift
      YARV.compile(ARGV.shift)
    else
      YARV.compile(ARGF.read, ARGF.filename, ARGF.path, ARGF.lineno)
    end

  queue = [compiled]
  while iseq = queue.shift
    puts "== disasm #<ISeq:#{iseq.name}>"

    iseq.insns.each do |insn|
      puts "0000 #{insn}"
      queue << insn.iseq if insn in YARV::DefineMethod
    end

    puts if queue.any?
  end

  return
end

# Check if we are reading directly from a string with -e.
compiled =
  if ARGV.first == "-e"
    ARGV.shift
    YARV.compile(ARGV.shift)
  else
    YARV.compile(ARGF.read, ARGF.filename, ARGF.path, ARGF.lineno)
  end

compiled.eval
